---
apiVersion: batch/v1
kind: Job
metadata:
  name: zap-baseline-scan-all
  namespace: petclinic
  labels:
    app: zap-scanner
    scan-type: baseline
spec:
  ttlSecondsAfterFinished: 7200
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: zap-scanner
        scan-type: baseline
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: zap-scanner
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /zap/wrk && chmod 777 /zap/wrk && chown -R 1000:1000 /zap/wrk']
        volumeMounts:
        - name: zap-reports
          mountPath: /zap/wrk
      containers:
      - name: zap
        image: ghcr.io/zaproxy/zaproxy:stable
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "========================================"
            echo "ZAP Baseline Scan - All Petclinic Services"
            echo "========================================"
            
            # Fix permissions
            chmod 777 /zap/wrk || true
            
            echo "Targets:"
            echo "  - API Gateway (main entry point): http://api-gateway:8080"
            echo "========================================"
            
            zap-baseline.py \
              -t http://api-gateway:8080 \
              -j \
              -r zap-baseline-report.html \
              -J zap-baseline-report.json \
              -w zap-baseline-report.md \
              -I || true
            
            echo ""
            echo "========================================"
            echo "Baseline Scan Completed!"
            echo "========================================"
            ls -lh /zap/wrk/
            
            echo ""
            echo "Shutting down Istio sidecar..."
            curl -X POST http://localhost:15020/quitquitquit || true
            sleep 5
        volumeMounts:
        - name: zap-reports
          mountPath: /zap/wrk
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: zap-reports
        hostPath:
          path: /tmp/zap-reports/baseline
          type: DirectoryOrCreate
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: zap-active-scan-all
  namespace: petclinic
  labels:
    app: zap-scanner
    scan-type: active
spec:
  ttlSecondsAfterFinished: 7200
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: zap-scanner
        scan-type: active
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: zap-scanner
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['sh', '-c', 'mkdir -p /zap/wrk && chmod 777 /zap/wrk && chown -R 1000:1000 /zap/wrk']
        volumeMounts:
        - name: zap-reports
          mountPath: /zap/wrk
      containers:
      - name: zap
        image: ghcr.io/zaproxy/zaproxy:stable
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "========================================"
            echo "ZAP Active Scan - All Petclinic Services"
            echo "========================================"
            
            # Fix permissions
            chmod 777 /zap/wrk || true
            
            echo "Targets:"
            echo "  - API Gateway (main entry point): http://api-gateway:8080"
            echo "========================================"
            
            zap-full-scan.py \
              -t http://api-gateway:8080 \
              -r zap-active-report.html \
              -J zap-active-report.json \
              -w zap-active-report.md \
              -I || true
            
            echo ""
            echo "========================================"
            echo "Active Scan Completed!"
            echo "========================================"
            ls -lh /zap/wrk/
            
            echo ""
            echo "Shutting down Istio sidecar..."
            curl -X POST http://localhost:15020/quitquitquit || true
            sleep 5
        volumeMounts:
        - name: zap-reports
          mountPath: /zap/wrk
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
      volumes:
      - name: zap-reports
        hostPath:
          path: /tmp/zap-reports/active
          type: DirectoryOrCreate
      restartPolicy: Never